FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache build-base python3 make

COPY package.json package-lock.json ./
RUN npm install

RUN apk del build-base python3 make

COPY . .
EXPOSE 3000
CMD ["npm", "start"]